services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: softy-pinko-back-end
    expose:
      - "5252"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: softy-pinko-front-end
    expose:
      - "9000"
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    container_name: softy-pinko-proxy
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end